### ISSUE TITLE
Which release for PHP 7.1

### ISSUE THREAD

**Issue by quantegy** [PhpGt/Dom#246]
At which release was PHP 7.1 still supported?

**Comment by g105b** [comment]
Hi @quantegy ,

The latest release that supported PHP 7.1 was [v1.1.0](https://github.com/PhpGt/Dom/releases/tag/v1.1.0). The main reason this repository was so keen and quick to adopt PHP 7.2 was due to how throughout the DOM's APIs, nullable return types are used very commonly, and I wanted to get the library working with native PHP type hinting as soon as possible.

For example, I'm talking about common functionality like `$document->getElementById("something")` - this method returns an `Element` or `null` if there is no element of matching ID "something".

PHP 7.2 was the first PHP release to support nullable returns natively, and we were super-keen to take advantage of this feature in the DOM library.

May I ask what is preventing your project to upgrade to PHP 7.2 or newer? There are very few considerations to know about between PHP 7.0, 7.1, 7.2, 7.3 and 7.4. The upgrade paths are really smooth, and it's always a good idea to keep your project up to date and in line with the [official supported PHP versions](https://www.php.net/supported-versions.php). PHP 7.1 stopped being officially supported by PHP in January 2020.

I would highly recommend upgrading your project to 7.4, and that way you can take advantage of newer releases to this library, of which a lot of recent ones I am very proud to have implemented. If you would like any help regarding upgrading your PHP version, I'm always happy to answer any questions.

**Comment by quantegy** [comment]
I am totally on board with that. I was testing locally, then deployed code to a dev site that ran 7.1.33. My local dev area is 7.2.x. So I am stuck with either removing any code that utilizes phpgt/dom or upgrading the PHP instance on the servers, which is not within my capacity to do. I figured I'd just rollback to older release until I can manage to do either of the aforementioned. Thanks.

**Comment by g105b** [comment]
I have a tip for your negotiation: PHP 7.2 is not an "edge" release. In fact, 7.2 is no longer in "active support" and instead it receives security fixes only, due to 7.2 being considered out of date.

Please forward this chart to your server admins: https://www.php.net/supported-versions.php

![image](https://user-images.githubusercontent.com/358014/76904995-f56b7780-6898-11ea-856a-54219baccf7c.png)
