### ISSUE TITLE
Support DOM methods of the HtmlTableElement

### ISSUE THREAD

**Issue by lfiweb** [PhpGt/Dom#260]
Feature request: It would be nice, if all the DOM methods of the HTMLTableElement such as insertRow() and of the HTMLTableRowElement such as insertCell() would be available (or did I overlook this?)

**Comment by g105b** [comment]
Hi @lfiweb , thanks for your suggestion.

You're not missing anything, this is not an implemented feature of the library due to the way inheritance works throughout, but I would like to explore adding this.

The problem is that PhpGt/Dom extends PHP's native DOMDocument, which is based off libxml2. Due to this, *all* Elements must be an instance of `Gt\Dom\Element`, which is a decision of libxml2, not one made by me.

There is currently no way of identifying between Element types apart from checking the Element::$tagName property, whereas in the perfect world, each Element would be an instance of its own type, allowing for each element type to optionally have its own properties and methods.

One way to overcome this would be to expose the `insertRow()` and `insertCell()` methods on all element types, throwing an exception if the methods are called on non-table elements. I think this is the most realistic approach.

The other way would be to have dynamic doc blocks, maybe through the use of Psalm.

The other-other way, which would be a lot of work, would be to implement our own DOM parser and throw away libxml completely. This is probably not a good idea, but I am tempted to try.

If we are going to go with option 1, would you be able to help me? I would like to get a list of all "custom" methods for different Element types, so they can be implemented over time and this library would then be 100% compatible with browser-based DOM. Is this something you could help me collate?

Cheers,
Greg.

**Comment by speich** [comment]
Hi Greg
Sorry for not answering sooner. By mistake I reported this request with my work project account, and not being at work much these days, I didn't see it until now. Thanks for providing a detailed explanation. I would be willing to help you compile a list of methods specific to certain element types, but be warned that I don't have a tons of time at hand (like you probably too).

**Comment by g105b** [comment]
Hi @speich,

That would be a fantastic help. Yes I'm the same as you - I would love to be able to afford more time on open source though.

Once we have a complete list of methods that are only applicable for specific HTML element types, we can think of the best approach for adding these into this repo.

I have two ideas of how to implement:

1) Keep it simple - apply all methods to all elements, throwing an exception if the tagName doesn't match the allowed element type.
2) Require the developer to subset manually, using something like `Document::getHTMLTableElement($element)`. I'm not a fan of this idea initially, but there could be a way of making this work with more thought.

I'd suggest looking at MDN as the source of truth for the method names. I'm not sure how many element-specific methods there are, so I don't know if this will be a quick task for you or one that you'll need help compiling. Either way, if you wanted to list them out here, that would be an incredible help.

**Comment by speich** [comment]
If think there might be quite a few additional methods (not all of them make probably sense such as the play() method on the HTMAudioElement inherited from the HTMLMediaElement). If I just pick some elements on MDN and look at the methods, many come with their own, e.g. HTMLHyperlinkElementUtils.toString(), HTMLFormElement.checkValidity(), HTMLFormElement.reportValidity(), HTMLFormElement.requestSubmit(), HTMLFormElement.reset(), submit(), HTMLImageElement.decode(), HTMLSelectElement has 9 methods

I could start compiling the following table:

name | method | applicable | implemented
--------|------------|---------------|------------------
HTMLAnchorElement | blur | no | no
HTMLAnchorElement | focus | no | no
HTMLAnchorElement | toString | yes | no

I would need your help to decide on applicable and implemented. Is this comment a good place to do this ? Can I come back and keep editing it ?

**Comment by speich** [comment]
Would it be of help if I added columns inherits from and implements, e.g.

name | method | applicable | implemented | inheritsFrom | implements |
--------|------------|---------------|------------------|-------------------|-----------------|
HTMLAnchorElement | blur | no | no | HTMLElement | HTMLHyperlinkElementUtils |
HTMLAnchorElement | focus | no | no  | HTMLElement | HTMLHyperlinkElementUtils |
HTMLAnchorElement | toString | yes | no  | HTMLElement | HTMLHyperlinkElementUtils |

**Comment by g105b** [comment]
This will be a really helpful resource! Having everything in one place like this is a great first step to help me implement the methods. I'm glad you put an applicable column, because there is no need for quite a few methods on the server, such as the blur/focus, as it has no meaning outside of the browser.

The HTMLFormElement validity functions would be interesting to implement with php.gt/domvalidation and the HTMLTemplateElement with php.gt/domtemplate - nothing extra for you to do, just making a note of it.

Let me know if this is too much work for you and we'll see if we can split it up. Thanks!

**Comment by speich** [comment]
So, here's the full list (hope I didn't miss anything):
name | method | applicable | implemented | inheritsFrom | implements |
--------|------------|---------------|------------------|-------------------|-----------------|
HTMLAreaElement | toString() | yes? | no? | HTMLElement | HTMLHyperlinkElementUtils |
HTMLAnchorElement | blur() | no | no | HTMLElement | HTMLHyperlinkElementUtils |
HTMLAnchorElement | focus() | no | no  | HTMLElement | HTMLHyperlinkElementUtils |
HTMLAnchorElement | toString() | yes | no  | HTMLElement | HTMLHyperlinkElementUtils |
HTMLAudioElement | - | - | - | HTMLMediaElement | - |
HTMLBRElement | - | - | - | HTMLElement | - |
HTMLBaseElement | - | - | - | HTMLElement | - |
HTMLBodyElement | - | - | - | HTMLElement | - |
HTMLButtonElement | checkValidity() | yes | no | HTMLElement | - |
HTMLButtonElement | reportValidity() | yes | no | HTMLElement | - |
HTMLButtonElement | setCustomValidity() | yes | no | HTMLElement | - |
HTMLCanvasElement | captureStream() | no | no | HTMLElement | - |
HTMLCanvasElement | getContext() | no | no | HTMLElement | - |
HTMLCanvasElement | toDataURL() | no | no | HTMLElement | - |
HTMLCanvasElement | toBlob() | no | no | HTMLElement | - |
HTMLCanvasElement | transferControlToOffscreen() | no | no | HTMLElement | - |
HTMLDListElement | - | - | - | HTMLElement | - |
HTMLDataElement | - | - | - | HTMLElement | - |
HTMLDialogElement | close() | no | no | HTMLElement | - |
HTMLDialogElement | show() | no | no | HTMLElement | - |
HTMLDialogElement | showModal() | no | no | HTMLElement | - |
HTMLDivElement | - | - | - | HTMLElement | - |
HTMLDocument | - | - | - | - | - |
HTMLElement | attachInternals() | ? | ? | HTMLElement | - |
HTMLElement | blur() | no | no | HTMLOrForeignElement | - |
HTMLElement | click() | no | no | Element | - |
HTMLElement | focus() | no | no | HTMLOrForeignElement | - |
HTMLElement | forceSpellCheck() | yes | no | Element | - |
HTMLEmbedElement | - | - | - | HTMLElement | - |
HTMLFieldSetElement | checkValidity() | yes | no | HTMLElement | - |
HTMLFieldSetElement | reportValidity() | yes | no | HTMLElement | - |
HTMLFieldSetElement | setCustomValidity() | yes | no | HTMLElement | - |
HTMLFormControlsCollection | namedItem() | yes | no | HTMLCollection | - |
HTMLFormElement | checkValidity() | yes | no | HTMLElement | - |
HTMLFormElement | reportValidity() | yes | no | HTMLElement | - |
HTMLFormElement | requestSubmit() | yes? | no | HTMLElement | - |
HTMLFormElement | reset() | yes | no | HTMLElement | - |
HTMLFormElement | submit() | yes | no | HTMLElement | - |
HTMLHRElement | - | - | - | HTMLElement | - |
HTMLHeadElement | - | - | - | HTMLElement | - |
HTMLHeadingElement | - | - | - | HTMLElement | - |
HTMLHtmlElement | - | - | - | HTMLElement | - |
HTMLIFrameElement | - | - | - | HTMLElement | - |
HTMLImageElement | decode() | yes? | no | HTMLElement | - |
HTMLInputElement | blur() | no | no | HTMLElement | - |
HTMLInputElement | click() | no | no | HTMLElement | - |
HTMLInputElement | focus() | no | no | HTMLElement | - |
HTMLInputElement | select() | yes? | no | HTMLElement | - |
HTMLInputElement | setSelectionRange() | yes? | no | HTMLElement | - |
HTMLInputElement | setRangeTex() | yes? | no | HTMLElement | - |
HTMLInputElement | setCustomValidity() | yes | no | HTMLElement | - |
HTMLInputElement | checkValidity() | yes | no | HTMLElement | - |
HTMLInputElement | reportValidity() | yes | no | HTMLElement | - |
HTMLInputElement | stepDown() | yes | no | HTMLElement | - |
HTMLInputElement | stepUp() | yes | no | HTMLElement | - |
HTMLLIElement | - | - | - | HTMLElement | - |
HTMLLabelElement | - | - | - | HTMLElement | - |
HTMLLegendElement | - | - | - | HTMLElement | - |
HTMLLinkElement | - | - | - | HTMLElement | LinkStyle |
HTMLMapElement | - | - | - | HTMLElement | - |
HTMLMediaElement | addTextTrack() | no? | no | HTMLElement | - |
HTMLMediaElement | captureStream() | no | no | HTMLElement | - |
HTMLMediaElement | canPlayType() | no? | no | HTMLElement | - |
HTMLMediaElement | fastSeek() | no | no | HTMLElement | - |
HTMLMediaElement | load() | no | no | HTMLElement | - |
HTMLMediaElement | pause() | no | no | HTMLElement | - |
HTMLMediaElement | play() | no | no | HTMLElement | - |
HTMLMediaElement | seekToNextFrame() | no | no | HTMLElement | - |
HTMLMediaElement | setMediaKeys() | no | no | HTMLElement | - |
HTMLMediaElement | setSinkId() | no | no | HTMLElement | - |
HTMLMetaElement | - | - | - | HTMLElement | - |
HTMLMeterElement | - | - | - | HTMLElement | - |
HTMLModElement | - | - | - | HTMLElement | - |
HTMLOListElement | - | - | - | HTMLElement | - |
HTMLObjectElement | checkValidity() | yes? | no |  HTMLElement | - |
HTMLObjectElement | setCustomValidity() | yes? | no |  HTMLElement | - |
HTMLOptGroupElement | - | - | - | HTMLElement | - |
HTMLOptionElement | Option() | yes | no? | HTMLElement | - |
HTMLOptionsCollection | - | - | - | HTMLCollection | - |
HTMLOutputElement | checkValidity() | ? | ? | HTMLElement | - |
HTMLOutputElement | reportValidity() | ? | ? | HTMLElement | - |
HTMLOutputElement | setCustomValidity() | ? | ? | HTMLElement | - |
HTMLParagraphElement | - | - | - | HTMLElement | - |
HTMLParamElement | - | - | - | HTMLElement | - |
HTMLPictureElement | - | - | - | HTMLElement | - |
HTMLPreElement | - | - | - | HTMLElement | - |
HTMLQuoteElement | - | - | - | HTMLElement | - |
HTMLProgressElement | - | - | - | HTMLElement | - |
HTMLScriptElement | - | - | - | HTMLElement | - |
HTMLSelectElement | add() | yes | no | HTMLElement | - |
HTMLSelectElement | checkValidity() | yes | no | HTMLElement | - |
HTMLSelectElement | item() | yes | no | HTMLElement | - |
HTMLSelectElement | namedItem() | yes | no | HTMLElement | - |
HTMLSelectElement | remove() | yes | no | HTMLElement | - |
HTMLSelectElement | reportValidity() | yes | no | HTMLElement | - |
HTMLSelectElement | setCustomValidity() | yes | no | HTMLElement | - |
HTMLSourceElement | - | - | - | HTMLElement | - |
HTMLSpanElement | - | - | - | HTMLElement | - |
HTMLStyleElement | - | - | - | HTMLElement | LinkStyle |
HTMLTableCaptionElement | - | - | - | HTMLElement | - |
HTMLTableCellElement | - | - | - | HTMLElement | - |
HTMLTableColElement | - | - | - | HTMLElement | - |
HTMLTableElement | createTHead() | yes | no | HTMLElement | - |
HTMLTableElement | deleteTHead() | yes | no | HTMLElement | - |
HTMLTableElement | createTFoot() | yes | no | HTMLElement | - |
HTMLTableElement | deleteTFoot() | yes | no | HTMLElement | - |
HTMLTableElement | createCaption() | yes | no | HTMLElement | - |
HTMLTableElement | deleteCaption() | yes | no | HTMLElement | - |
HTMLTableElement | deleteRow() | yes | no | HTMLElement | - |
HTMLTableElement | insertRow() | yes | no | HTMLElement | - |
HTMLTableRowElement | deleteCell() | yes | no | HTMLElement | - |
HTMLTableRowElement | insertCell() | yes | no | HTMLElement | - |
HTMLTableSectionElement | deleteRow() | yes | no | HTMLElement | - |
HTMLTableSectionElement | insertRow() | yes | no | HTMLElement | - |
HTMLTemplateElement | - | - | - | HTMLElement | - |
HTMLTextAreaElement | blur() | no | no | HTMLElement | - |
HTMLTextAreaElement | focus() | no | no | HTMLElement | - |
HTMLTextAreaElement | select() | yes? | no | HTMLElement | - |
HTMLTextAreaElement | select() | yes? | no | HTMLElement | - |
HTMLTextAreaElement | setRangeText() | yes? | no | HTMLElement | - |
HTMLTextAreaElement | setSelectionRange() | yes? | no | HTMLElement | - |
HTMLTextAreaElement | checkValidity() | yes | no | HTMLElement | - |
HTMLTextAreaElement | reportValidity() | yes | no | HTMLElement | - |
HTMLTextAreaElement | setCustomValidity() | yes | no | HTMLElement | - |
HTMLTimeElement | - | - | - | HTMLElement | - |
HTMLTitleElement | - | - | - | HTMLElement | - |
HTMLTrackElement | - | - | - | HTMLElement | - |
HTMLUListElement | - | - | - | HTMLElement | - |
HTMLUnknownElement | - | - | - | HTMLElement | - |
HTMLVideoElement | getVideoPlaybackQuality() | no | no | HTMLMediaElement | - |
HTMLVideoElement |requestPictureInPicture() | no | no | HTMLMediaElement | - |

**Comment by g105b** [comment]
@speich - thank you for your efforts! While the list is quite a long one, there are actually less element-specific methods than I was expecting. Because of this, I personally think it would be OK to expose these methods on the `Gt\Dom\Element` object, throwing an exception if the method is not appropriate for the type of element. Would you agree, or can you think of any better approach?

**Comment by g105b** [comment]
An example of what could cause some confusion:

```php
$headerImage = $document->querySelector("body>header>img");
// This method will be shown in the IDE:
$headerImage->createTFoot();
// An exception would be thrown "createTFoot is only available on <table> elements".
```

**Comment by speich** [comment]
I also thought that that there would be more exceptions :-) 

Generally I agree, that one can live with the overhead of adding these methods to the element and just throwing an error.

I would say the element specific methods are basically the form (validation) methods, the add/remove of the HTMLSelectElement    and the table (creation) methods. I normally use them only in a special context, such as form validation or to construct tables. 

I haven't thought this through, but couldn't we add the element specific methods only on the fly when accessing them, e.g. `$table = document.querySelector('table')` or `$form = document.createElement('select')`, etc... ?

Note: I haven't used the library yet, so I'm not really familiar with it (I'm pretty used to using the DOM in JavaScript and the PHP DOMDocument).

**Comment by g105b** [comment]
Adding the functions on-the-fly is a neat idea, but it would require Reflection and possibly slow the library down. It might not be obvious to developers either, and the IDE wouldn't be able to show code completion for this.

This library is an extension of the PHP DOMDocument, with the intention of matching the JavaScript API as closely as possible. The DOMDocument defines how the classes are used though, for Node/Element/etc. so that's why we're stuck at putting this functionality onto the Element class. Unless you fancy writing your own HTML parser and XPath implementation, we're stuck at using DOMDocument as libxml2 ships with PHP.

**Comment by speich** [comment]
Then what about explicitly having to use them:
```
class HTMLDocumentExtended extends HTMLDocument {
  // all element specific methods
  ...
}
$document = new \Gt\Dom\HTMLDocumentExtended();
```
Now, at least I should not be confused by all the extra methods on all elements, since I instantiated the extended version?

**Comment by g105b** [comment]
Unfortunately, DOMDocument has a really strange class model which means that this isn't really possible.

Each class within Gt\Dom is registered with DOMDocument to use as the extended class, so instead of DOMDocument creating `DOMElement` objects, it created `Gt\Dom\Element` instead. The same goes for `Node`, `Attr`, and all of the classes, including `Document` itself.

There are always ways around these things, but I think that introducing another class to encapsulate this functionality would lower the readability and developer experience. I personally think having the methods available on the `Element` is fine, but it's a great idea to explore all possibilities before an implementation is started.

**Comment by g105b** [comment]
Hi @speich ,

I've been thinking about the future of this repository and have decided the following:

A minor version increase will be made to include all the methods you have listed in this thread on the Element object.

The next major version increase will be to remodel the object hierarchy completely, as described in #261 - to implement PhpGt/Dom as a facade to DOMDocument rather than an extension of it.

Let me know your thoughts. It might be a chunk of work, but I think it would be worth it.

Cheers,
Greg.

**Comment by speich** [comment]
Sounds like a good and reasonable solution. 
Simon

**Comment by g105b** [comment]
Just letting you know that I've started implementation on this feature as part of #261 .

**Comment by speich** [comment]
cool :-))

**Comment by g105b** [comment]
@speich wow, that took me ages! I've pushed to branch [facade](https://github.com/PhpGt/Dom/tree/facade) (open as a draft PR #266) all the classes of HTMLDocuments with their documented properties, magic getters/setters and methods.

I've purposefully missed out the methods of classes that have no meaning on the server, and I've missed out any properties that have been deprecated or are obsolete.

It would be a huge help if you could take a look at the classes I've pushed to that branch and check against their linked MDN documentation (each class has a `@link` comment at the top of it to the relevant documentation.

I'm sure there are typos and mistakes, but hopefully I'll find and fix these when I come to unit test everything - but it would be super useful for you and anyone else who's interested to take a quick glance over everything so far.

**Comment by speich** [comment]
Greg, I just started comparing the documentation to MDN. What should I do with links to MDN, where there is no documentation (yet) ? Is it ok, if they (currently) lead to 404, but might exist later or should I remove them, .e.g.:

@link https://developer.mozilla.org/en-US/docs/Web/API/Attr/name
Attr:__prop_get_name()

does not have its own documentation page.

**Comment by speich** [comment]
other question. Should I document arguments of setters with @param and return types with @return of getters, e.g.:
```php
/**
  * @link https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/data
  * @return string DOMString representing the textual data contained in this object.
*/
protected function __prop_get_data():string {
  return $this->getNativeNode()->data;
}

/** @link https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/data
 * @param string $data DOMString representing the textual data contained in this object.
 */
public function __prop_set_data(string $data):void {
  $this->getNativeNode()->data = $data;
}
```
or is that to redundant.

**Comment by g105b** [comment]
> What should I do with links to MDN, where there is no documentation (yet) ?

I did actually make my first contribution to MDN to fill in some of the blanks, but then I realised that there are so many missing pieces of the DOM documentation...

I'm not sure what the best thing to do is here... MDN is definitely the best source for documentation for anything web related, but even having said that, you can see how many missing pieces there are... maybe it's acceptable to leave them 404 for now, and maybe contribute some links over time if possible?

> Should I document arguments of setters with @param and return types with @return of getters

The parameters are documented at the top of the class - this is so that IDEs can pick up the actual parameters without needing to expose the __prop_get_* functions. I've essentially just copied the MDN documentation into this place, and I personally think that just a `@link` back to MDN on the getter/setter function is ample... but I'm open to feedback on this.

If you take a look at PR #266 you'll see that I've been plodding through adding unit tests to every area of the DOM, whenever I get some free time, and I'll soon be getting to the HTMLTableElement functionality! Feel free to create some failing unit tests for me to implement if you want. Take a look at the `ElementTest`, `ParentNodeTest` and `DocumentTest` classes for how I've been adding unit tests this week.

**Comment by g105b** [comment]
@speich FYI, I've unit tested *everything* in the new Facade apart from the new HTMLElement class extensions. I've left these until last so I can think about the questions you asked some more.

To address your question about the missing MDN documentation, I think we should also add a link to the W3C definition, which follows this URL syntax: 

+ MDN missing link: https://developer.mozilla.org/en-US/docs/Web/API/Attr/name
+ W3C spec: https://dom.spec.whatwg.org/#dom-attr-name

I'm going to start unit testing everything in the HTMLElement directory soon, and I'll push each test class as I create it. This will make it easy for others to help me out writing tests if they want to, without clashing.

As I write the tests, I will add the link to the W3C spec for every property and method. I hope this makes sense. Please let me know if you have any feedback, and feel free to write a unit test or two if you fancy.

**Comment by speich** [comment]
I've started to play around and noticed that when I append a (div) tag to the html document, it is created with the NS, which is probably not intended (because $document is an instance o HTMDocument in: https://github.com/PhpGt/Dom/blob/4a28d03caee00aab81ef5ed2e7236c772a0025c6/src/Document.php#L349

```php
$html = '<html lang="en"><head><title>Test</title></head><body></body></html>';
$document = HTMLDocumentFactory::create($html);

// and why is the constructor protected, so I use the factory, or should I create the document differently ?
// $document = new HTMLDocument($html);

$div = $document->createElement('div');
$document->body->appendChild($div);
var_dump($document->body->innerHTML);
```

**Comment by g105b** [comment]
Hi @speich,

The reason for the protected constructor is simply to match the W3C specification. It's prohibited for any `Node` type to be constructed directly (including a `Document` node), so I've created the factory as a mechanism for creating a Document of the required type.

However, I've also matched the mechanism of using a `DOMParser` to create a Document from a string (`$parser = new DOMParser(); $document = $parser->parseFromString($html, "text/html");`). This is the preferred method as it matches the W3C standard, but I've been using the factory throughout the unit tests to limit the footprint of each test.

The namespace issue you've raised is a bug that I've introduced in the process of implementing this facade. I've isolated and fixed the issue into its own unit test here: https://github.com/PhpGt/Dom/blob/e26f628bd083c608764c012402f419873baf5896/test/phpunit/HTMLDocumentTest.php#L26-L34

Please pull the `facade` branch and you'll get the fix.

**Comment by g105b** [comment]
I've just pushed a few commits to test the base `HTMLElement` class. It'll take a while to get through all the HTMLElement class extensions, but I'll try to do at least one class per day.

If you would like to implement and test the `HTMLTableElement` functionality, I'll leave these classes until the end. Would be great to get an extra pair of hands on this as it's a big code change. Hopefully we'll see everything complete within about a week from now.

**Comment by speich** [comment]
I'll give it a try.
