### ISSUE TITLE
Order of child elements in HTMLTableElement

### ISSUE THREAD

**Issue by speich** [PhpGt/Dom#270]
I'm struggling with the spec of the HTMLTableElement, especially with the order of child elements. According to the latest html5.2 spec https://www.w3.org/TR/html52/tabular-data.html#tabular-data the content model  should be:

> In this order: optionally a caption element, followed by zero or more colgroup elements, followed optionally by a thead element, followed by either zero or more tbody elements or one or more tr elements, followed optionally by a tfoot element, optionally intermixed with one or more script-supporting elements.

So far so good, but now comes the confusing part, that seems to contradict this:
https://www.w3.org/TR/html52/tabular-data.html#dom-htmltableelement-createthead

> The createTHead() method must return the first thead element child of the table element, if any; otherwise a new thead element must be created and inserted immediately before the first element in the table element that is neither a caption element nor a colgroup element, if any, **or at the end of the table if there are no such elements**, and then that new element must be returned.

So if my table has a tbody element, the thead element would come after it !?

**Comment by g105b** [comment]
The W3C specs are really difficult to read due to their verbosity... but after reading this a few times I can see the answer. 

Working with this kind of text is an unfortunate necessity when working with W3C documents. But at least it's not legalese!

The vital wording that makes this sentence complicated is "that is neither". It's reversing the logic of the sentence. 

> inserted immediately before the first element in the table element that **is neither** a caption element nor a colgroup element

So if there's a `<tr>` in there already, insert the THEAD before it, because a TR is neither a caption or a colgroup.

The other confusing bit is that it uses the terminology "at the end of the table". After exploring other terminology options, I actually can't think of a better way of stating it so that it hits all the points. It's saying at the end of the table if there are no non-caption and no non-colgroup elements. So if there is a caption, but nothing else, the thead needs to be added at the end of the table.

I really hope this helps. My brain hurts.

**Comment by speich** [comment]
Thanks, your *neither* and a good night's sleep helped

**Comment by g105b** [comment]
This functionality has [some tests](https://github.com/PhpGt/Dom/blob/a8c99b0ce9c1a1e4e8a36f39cb2bf9c2a239e3ed/test/phpunit/HTMLElement/HTMLTableElementTest.php#L32-L42) backing it up now so I'm closing the issue.
