### ISSUE TITLE
LibXML bug dealing with <script> tags containing strings of HTML

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#39]
This is an issue with the underlying libxml implementation, but it should be this repo's responsibility to fix.

```php
<?php

$html = <<<HTML
<!doctype html>
<h1>Hello!</h1>

<script>
// here is some HTML enclosed in strings within the script tag.
// but when the DOMDocument is output, the div tags are stripped/manipulated... why?
var startingTag = '<div>';
var endingTag = '</div>';
</script>

<h2>Goodbye!</h2>
HTML;

$document = new DOMDocument("1.0", "utf-8");
libxml_use_internal_errors(true);
$document->loadHTML($html);
echo $document->saveHTML();
```

Outputs:
```
<!DOCTYPE html>
<html><body><h1>Hello!</h1>

<script>
// here is some HTML enclosed in strings within the script tag.
// but when the DOMDocument is output, the div tags are stripped/manipulated... why?
var startingTag = '<div>';
var endingTag = '';
</script><h2>Goodbye!</h2></body></html>
```

Notice that the ending tag within the string is removed by libxml. It's going to be a hack to fix this without replacing libxml, but a useful hack nonetheless.

**Comment by j4m3s** [comment]
Is this an open bug on libxml then?

**Comment by g105b** [comment]
Everyone is blaming other repositories/standards. My view is to fix it in PHP.Gt's implementation as and when it comes up.

**Comment by j4m3s** [comment]
My first reaction is that you shouldn't be working-around a bug in another repo, just patch it upstream with a PR.  But it looks like you'd be digging around in the guts of php!

Did you hit this issue with php.gt v1?  If it's not a pressing issue you could always list it as a known limitation until the defect gets fixed in libxml - or someone squeals that they need it fixed.

**Comment by g105b** [comment]
Not a PHP bug. Too broad to try and cover here.
