### ISSUE TITLE
HTMLDocument and XMLDocument re-declare their use of LiveProperty and ParentNode

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Dom#75]
This shouldn't be necessary as their parent (Document) already specifies that it uses them.  Simply removing the re-declarations causes an error as below, which indicates there's something wrong in the design of the traits.  It's probably just that the trait methods should be protected rather than private so that the subclasses can use them (a la Open-Closed principle), but I didn't want to just make that change without raising it first.

```
Gt\Dom\NonDocumentTypeChildNodeTest::testElementSiblings
Error: Call to private method Gt\Dom\HTMLDocument::prop_get_body() from context 'Gt\Dom\Document'

dom/src/LiveProperty.php:24
dom/src/LiveProperty.php:14
dom/test/NonDocumentTypeChildNode.test.php:25
```

**Comment by g105b** [comment]
Good catch, I think you're right in that the prop_get_body function will be available if it were protected and only the top class used the trait.

**Comment by g105b** [comment]
This is one of those weird libxml things, but both HTMLDocument and XMLDocument need to use the trait, because the inheritance is muddied due to the use of DOMDocument::registerNodeClass.

While Gt\Dom\HTMLDocument does extend Gt\Dom\Document, in real-world use the trait is not always accessible for the above reason.
